kind: Pod
apiVersion: v1
metadata:
  name: fio-$N
  labels:
    app: fio
spec:
  nodeSelector:
    kubernetes.io/hostname: ksnode-2
  # Run on a storage node so that the nexus is local to the app
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: pvc-$N
  containers:
    - name: fio
      image: mayadata/fio
      args:
        - sleep
        - "1000000"
      volumeDevices:
        - devicePath: /dev/xvda
          name: ms-volume
