kind: Pod
apiVersion: v1
metadata:
  name: fio-$N
  labels:
    app: fio
spec:
  nodeSelector:
    kubernetes.io/hostname: node-0-119170
  # Run on a storage node so that the nexus is local to the app
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: basic-vol-io-2r-ext4-thick-bindimm
  containers:
    - name: fio
      image: mayadata/fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/volume"
          name: ms-volume
      #volumeDevices:
      #  - devicePath: /dev/xvda
      #    name: ms-volume
