kind: Pod
apiVersion: v1
metadata:
  name: fio-ro-$N
  labels:
    app: fio
spec:
  #nodeSelector:
  #  kubernetes.io/hostname: rawfile-worker
  # Run on a storage node so that the nexus is local to the app
  volumes:
    - name: ms-volume
      persistentVolumeClaim:
       claimName: pvc-1
       readOnly: true
  containers:
    - name: fio
      securityContext:
        privileged: true
      image: mayadata/fio
      args:
        - sleep
        - "1000000"
      volumeDevices:
        - devicePath: /dev/xvda
          name: ms-volume
