kind: Pod
apiVersion: v1
metadata:
  name: fio-test-$N
  labels:
    app: fio
spec:
  nodeSelector:
    kubernetes.io/hostname: kind-worker2
  # Run on a storage node so that the nexus is local to the app
  volumes:
    - name: var-lib
      hostPath:
        path: /var/lib
        type: Directory
  containers:
    - name: fio
      image: mayadata/fio
      args:
        - sleep
        - "1000000"
      volumeMounts:
        - mountPath: "/var/lib"
          name: var-lib
          #mountPropagation: HostToContainer
      #volumeDevices:
      #  - devicePath: /dev/xvda
      #    name: ms-volume
