kind: Pod
apiVersion: v1
metadata:
  name: fio-1
  labels:
    app: fio
spec:
  nodeSelector:
    kubernetes.io/hostname: worker-0
  # Run on a storage node so that the nexus is local to the app
  volumes:
    - name: ms-volume-1
      persistentVolumeClaim:
       claimName: pvc-1
    - name: ms-volume-2
      persistentVolumeClaim:
       claimName: pvc-2
  containers:
    - name: fio
      securityContext:
        privileged: true
      image: mayadata/fio
      args:
        - sleep
        - "1000000"
      volumeDevices:
        - devicePath: /dev/xvda1
          name: ms-volume-1
        - devicePath: /dev/xvda2
          name: ms-volume-2
