apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-$N
spec:
  accessModes:
   - ReadWriteOnce
  # Change to "Block" for raw block device
  volumeMode: Block
  resources:
    requests:
      storage: 64Mi
  storageClassName: mayastor-nvmf
