apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-$N
  namespace: ${NS:-default}
spec:
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: $SZ
  storageClassName: $SC
