apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-$N
spec:
  accessModes:
   - ReadWriteOnce
  # Change to "Block" for raw block device
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: $SC
