apiVersion: "openebs.io/v1beta3"
kind: DiskPool
metadata:
  name: pool-$NODE
  namespace: $NAMESPACE
spec:
  node: $NODE
  disks: ['$DISK']
  encryptionConfig:
    source:
      secret:
        name: pool-encr-secretx
